#cloud-config
# https://www.techrepublic.com/article/how-to-install-neo4j-ubuntu-server/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCPIIO8uY8oWIihDv0tCAbX6toyG1RYkaLZyfGD1L+I07K4CnwAVBSU+81vw3Yv5sN9tj2Ccve9kzEeCNMld2mDP/Tt7edkx2MCToVfVx+njqwY/XbMY9bfdRKJLhIoLavuVNLnnkSIXdtlGr3JF71hPHzBDMEo64ofPCQ8hPsGxL1u3efb12jcWcRhudKtv7Qh6cVE47Zj4xImfi6VlLqwzcKZ5oCqR/z1hLLL+/pS3eM5Qsor5wmAqNfH4+z5eE+pOkFm7a0Nkygv9jwXIqtJzFGKYDe6ciBD04pEovdvY0FTyiv2vksQOVgjtu2faG2Iv1HOG0JktCIwJ49OEgjT teacher-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCu5Yg4KRg7hzYOsp9lVnxggcrhiBk3nuB+5hY+Zwys14tj2C5dEPzCHaA5T7bcg8g1haJzPaVoNuJX7oZf+VryV+gkcN649QNC7bHD8zIviLzyqo94/w5Xh+bu1WGD6NUE9FJRcMQFCsGNV4IuTY2Xy6SEO1MWMqZlKrgOtp8B5wHZtXrDI20aAYL+g6Yxpv7VH6v/75Bk2nUiGW/zQ7S0t3JUBp3j7JndTZYy/hiPUVnO66XoJeYDSAvxY8SuvQFFSrwiaN6+sVG5OnFUdOZLrvSR8pfvrKfNmwfn/rBcWRQ1mgIMEZJzp1w9y2Yi1baT8y18rtQ4t9iL3RU8v+XJ aws-key
ssh_pwauth: false
disable_root: false    
package_update: true 
packages:
  - unzip
  - gnupg
  - curl
runcmd:
  - curl -fsSL https://debian.neo4j.com/neotechnology.gpg.key |sudo gpg --dearmor -o /usr/share/keyrings/neo4j.gpg
  - echo "deb [signed-by=/usr/share/keyrings/neo4j.gpg] https://debian.neo4j.com stable latest" | sudo tee -a /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update -y
  - sudo apt install neo4j -y
  - sudo systemctl enable neo4j.service
  - sudo systemctl start neo4j.service
  - sudo sed -i 's/#server.default_listen_address/server.default_listen_address/g' /etc/neo4j/neo4j.conf
  - sudo systemctl restart neo4j.service
# default username and password are "neo4j" (without the quotes)